language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - npm install kelda/deployment-engine-downloader && ./node_modules/.bin/kelda-downloader

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint
    - ./kelda inspect ./nginxExampleWithInfra.js graphviz

notifications:
    slack:
        secure: e4lX4sjKkM3FXDmXG9fv/mERgy1W3ARfXKyq7QwnefvqR95xTLaU5/C5meYlXLmyq1BLWHU9sTR/tZzPXF0dc3PMkuxcs9NgZG/FZlcEY+eUwHKG8qN16a4K3egBoEOvfP/Pli5HdwOFidf1HlIAp/Vlcig7Jxlz93vEbIu+WoZWFWDMVtzCOsEVvpFOdvU35MYFhHyRQN4PDk6lM391tpi39G66MuMYeTIVV7CJQD3fBSPpngPYGGFEkCBeDo4SCA2xb5g75bPzTFOEUWuRueorIC4DjWjwelNQRzK1f/4MyyCWfUpQUhYGQmkjmy3TPLcRCPvYDz7HPq+QO4Jx4aHpdpFH92O2PvT+bStoVCjaXfHl1C1JmACH0AtTJilPmqwN/Mw+eHYeWPSPgFR0+C7EW6EiDpryEeB0r/bI8imgVINb1CgsYO5VsFyQ1c9ciDNgctPIGC//QhOjTC2++X85nOT7z/uSnJ4NEGanx0JyMgW95RqfyquLUTz30pzmXGbi9CqzgNJlLhW9qmhCaC65oz/TW4HtUw/e/9Y+HwUgHTgBv95KubvtVsubA1fths0KeD04xg/7YaUTiDZlgi6o400SPCFtk4N7tQMysMbvAL+23QRb8mn5bId/hgIhRfw/sWKfS1B7LVnNLg3l8KXZDaPW9Z+VGxOCXfjxH8M=
